[monitor:///var/log/syslog]
index = main
sourcetype = linux_secure
  
[monitor:///var/log/auth.log]
index = main
sourcetype = linux_secure

# For CentOS (Red Hat, RHEL, Rocky Linux, AlmaLinux) uncomment below 2 lines
# [monitor:///var/log/secure]
# index = main
# sourcetype = linux_secure

  
# Optional I already had snort configured so I added this, You can delete this or change the path as per your ids/ips
[monitor:///var/log/snort/snort.log]
index = main
sourcetype = linux_secure
