[tcpout]
defaultGroup = default-autolb-group

[tcpout:default-autolb-group]
server = Your_Receiver_IP:9997


# Use this comand instead
# before using this be on splunkforwarder/bin directory
# ./splunk add forward-server reciver_ip/port_number_of_reciever
